/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.ReceptionRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.InvestigationOrganization;
import Business.Organization.Organization;
import Business.Organization.QuarantineOrganization;
import Business.Organization.ReceptionOrganization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.WorkRequest_quarantineCDC;
import Business.WorkQueue.WorkRequest_receptionInvestigation;
import People.People;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Component;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellRenderer;

/**
 *
 * @author stacyhuang
 */
public class ReceptionWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ReceptionWorkAreaJPanel
     */
     private JPanel jpanel;
     private ReceptionOrganization organization;
     private Enterprise enterprise;
     private UserAccount userAccount;
     private EcoSystem system;
     private People thispeople;
    private WorkRequest_quarantineCDC thisrequest;
    private ArrayList<Integer>ar= new ArrayList();
    private ArrayList<Integer>ar1= new ArrayList();
    private Network network;
    
    public ReceptionWorkAreaJPanel(JPanel jpanel, UserAccount userAccount, ReceptionOrganization organization, Enterprise enterprise, EcoSystem system,Network network) {
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        initComponents();
        this.jpanel = jpanel;
        this.organization = organization;
        this.enterprise = enterprise;
        this.userAccount = userAccount;
        this.system=system;
        this.network=network;
        popPatientTable();
        sendbtn.setEnabled(false);
        messagearea.setEditable(false);
        setFieldEdible(false);
        pop();
        pop2();
        a.setBackground(Color.RED);
        b.setBackground(Color.ORANGE);
        c.setBackground(Color.WHITE);
    }
    
   public void pop(){
    for(WorkRequest_quarantineCDC request:organization.getWorkQueue_quarantineCDC().getWorkRequestList()){
           if(request.getSymptons().contains("DEATH")){
           ar.add(request.getCaseNumber());
          
           }    
    
    }
   
   }
   public void pop2(){
    for(WorkRequest_quarantineCDC request:organization.getWorkQueue_quarantineCDC().getWorkRequestList()){
           if(request.getSymptons().contains("HOSPITALIZED")){
           ar1.add(request.getCaseNumber());
       //  System.out.println(ar1);
          
           }    
    
    }
   
   }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        patientTable = new javax.swing.JTable()
        {
            @Override

            public Component prepareRenderer (TableCellRenderer renderer, int rowIndex, int columnIndex){
                Component componenet = super.prepareRenderer(renderer, rowIndex, columnIndex);

                Object value = getModel().getValueAt(rowIndex,columnIndex);

                if(columnIndex == 0){
                    if(ar.indexOf(Integer.parseInt(value.toString()))>-1){
                        componenet.setBackground(Color.RED);
                        componenet.setForeground(Color.BLACK);
                    }
                    else if(ar1.indexOf(Integer.parseInt(value.toString()))>-1){
                        componenet.setBackground(Color.ORANGE);
                        componenet.setForeground(Color.BLACK);}

                    else {componenet.setBackground(Color.WHITE);
                        componenet.setForeground(Color.BLACK);

                    }
                }
                return componenet;
            }

        }
        ;
        jLabel2 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        symptonfield = new javax.swing.JTextArea();
        sendbtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        phonefield = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        addressfield = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        statefield = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        countyfield = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        birthfield = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        agefield = new javax.swing.JTextField();
        selectbtn = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        messagearea = new javax.swing.JTextArea();
        backbtn = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        a = new javax.swing.JTextField();
        b = new javax.swing.JTextField();
        c = new javax.swing.JTextField();

        setBackground(new java.awt.Color(0, 102, 153));
        setForeground(new java.awt.Color(0, 102, 153));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        patientTable.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        patientTable.setForeground(new java.awt.Color(0, 153, 204));
        patientTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Case Number", "Diagnos Date", "Hospital", "Patient ID", "Name", "Gender", "processor", "status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        patientTable.setGridColor(new java.awt.Color(0, 102, 153));
        patientTable.setSelectionBackground(new java.awt.Color(204, 204, 204));
        patientTable.setSelectionForeground(new java.awt.Color(0, 0, 102));
        jScrollPane1.setViewportView(patientTable);
        if (patientTable.getColumnModel().getColumnCount() > 0) {
            patientTable.getColumnModel().getColumn(0).setResizable(false);
            patientTable.getColumnModel().getColumn(1).setResizable(false);
            patientTable.getColumnModel().getColumn(2).setResizable(false);
            patientTable.getColumnModel().getColumn(3).setResizable(false);
            patientTable.getColumnModel().getColumn(4).setResizable(false);
            patientTable.getColumnModel().getColumn(5).setResizable(false);
            patientTable.getColumnModel().getColumn(6).setResizable(false);
            patientTable.getColumnModel().getColumn(7).setResizable(false);
        }

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, 1090, 188));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 153, 204));
        jLabel2.setText("Symptons");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 330, -1, -1));

        jScrollPane3.setForeground(new java.awt.Color(0, 153, 204));

        symptonfield.setColumns(20);
        symptonfield.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        symptonfield.setForeground(new java.awt.Color(0, 153, 204));
        symptonfield.setRows(5);
        jScrollPane3.setViewportView(symptonfield);

        add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 370, 219, -1));

        sendbtn.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        sendbtn.setForeground(new java.awt.Color(255, 153, 51));
        sendbtn.setText("Send to Investigation");
        sendbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendbtnActionPerformed(evt);
            }
        });
        add(sendbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 600, 290, 80));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 204));
        jLabel1.setText("phone");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 300, -1, -1));

        phonefield.setForeground(new java.awt.Color(0, 153, 204));
        add(phonefield, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 340, 268, -1));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 153, 204));
        jLabel3.setText("address");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 380, -1, -1));

        addressfield.setForeground(new java.awt.Color(0, 153, 204));
        add(addressfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 420, 268, -1));

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 153, 204));
        jLabel4.setText("state");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 460, -1, -1));

        statefield.setForeground(new java.awt.Color(0, 153, 204));
        add(statefield, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 490, 120, -1));

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 153, 204));
        jLabel6.setText("county");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 460, -1, -1));

        countyfield.setForeground(new java.awt.Color(0, 153, 204));
        add(countyfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 490, 140, -1));

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 153, 204));
        jLabel7.setText("birthday");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 530, -1, -1));

        birthfield.setForeground(new java.awt.Color(0, 153, 204));
        add(birthfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 570, 268, -1));

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 153, 204));
        jLabel8.setText("age");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 610, -1, -1));

        agefield.setForeground(new java.awt.Color(0, 153, 204));
        add(agefield, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 650, 268, -1));

        selectbtn.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        selectbtn.setForeground(new java.awt.Color(255, 153, 51));
        selectbtn.setText("select");
        selectbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectbtnActionPerformed(evt);
            }
        });
        add(selectbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 280, 150, 40));

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 153, 204));
        jLabel9.setText("message from quarantine inspector");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 330, -1, -1));

        jScrollPane2.setForeground(new java.awt.Color(0, 153, 204));

        messagearea.setColumns(20);
        messagearea.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        messagearea.setForeground(new java.awt.Color(0, 153, 204));
        messagearea.setRows(5);
        jScrollPane2.setViewportView(messagearea);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 370, -1, -1));

        backbtn.setBackground(new java.awt.Color(255, 255, 255));
        backbtn.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        backbtn.setForeground(new java.awt.Color(255, 153, 51));
        backbtn.setText("back");
        backbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backbtnActionPerformed(evt);
            }
        });
        add(backbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 310, -1, -1));

        jLabel13.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 153, 204));
        jLabel13.setText("Death");
        add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 420, -1, 20));

        jLabel14.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 153, 204));
        jLabel14.setText("Hospitalized");
        add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 460, -1, -1));

        jLabel15.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 153, 204));
        jLabel15.setText("Self Quaratine");
        add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 500, -1, -1));

        a.setBackground(new java.awt.Color(255, 0, 0));
        a.setForeground(new java.awt.Color(0, 153, 204));
        add(a, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 420, 100, 20));

        b.setBackground(new java.awt.Color(255, 204, 51));
        b.setForeground(new java.awt.Color(0, 153, 204));
        b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bActionPerformed(evt);
            }
        });
        add(b, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 460, 100, 20));

        c.setForeground(new java.awt.Color(0, 153, 204));
        add(c, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 500, 100, 20));
    }// </editor-fold>//GEN-END:initComponents

    private void setFieldEdible(boolean boo){
        phonefield.setEditable(boo);
            addressfield.setEditable(boo);
            statefield.setEditable(boo);
            countyfield.setEditable(boo);
            birthfield.setEditable(boo);
            agefield.setEditable(boo);
            symptonfield.setEditable(boo);
    }
    private void setFieldText(String s){
        phonefield.setText(s);
            addressfield.setText(s);
            statefield.setText(s);
            countyfield.setText(s);
            birthfield.setText(s);
            agefield.setText(s);
            symptonfield.setText(s);
    }
    private void selectbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectbtnActionPerformed
        // TODO add your handling code here:
        int select=patientTable.getSelectedRow();
        if(select<0){
            JOptionPane.showMessageDialog(null, "please select");
            return;
        }else{
            WorkRequest_quarantineCDC request=(WorkRequest_quarantineCDC) patientTable.getValueAt(select, 0);
            this.thispeople=request.getPatient();
            this.thisrequest=request;
            phonefield.setText(thispeople.getPhone());
            addressfield.setText(thispeople.getAddress());
            statefield.setText(thispeople.getState());
            countyfield.setText(thispeople.getCounty());
            birthfield.setText(thispeople.getBirthday());
            agefield.setText(String.valueOf(thispeople.getAge()));
            symptonfield.setText(request.getSymptons());
            messagearea.setText(request.getMessage());
            messagearea.setEditable(true);
            sendbtn.setEnabled(true);
        }
    }//GEN-LAST:event_selectbtnActionPerformed

    private void sendbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendbtnActionPerformed
        // TODO add your handling code here:
          InvestigationOrganization invesorg=null;
        for(Organization o:enterprise.getOrganizationDirectory().getOrganizationList()){
                if(o instanceof InvestigationOrganization){
                    invesorg=(InvestigationOrganization)o;
                    break;
                }
            }
        if(thisrequest.getReceiver()!=null){
            JOptionPane.showMessageDialog(null, "already sent to investigation");
            return;
        }else{
            Date date =new Date();
            thisrequest.setReceiver(userAccount);
            WorkRequest_receptionInvestigation toInvestigation=new WorkRequest_receptionInvestigation();
            toInvestigation.setCaseNumber(thisrequest.getCaseNumber());
            toInvestigation.setHospital(thisrequest.getEnterprise());
            toInvestigation.setPatient(thisrequest.getPatient());
            toInvestigation.setSender(userAccount);
            toInvestigation.setSymptons(thisrequest.getSymptons());
            toInvestigation.setStatus("pending");
            toInvestigation.setDiagnosisDate(thisrequest.getDate());
            toInvestigation.setSentDate(date);
            toInvestigation.setMessage(messagearea.getText());
            thisrequest.setStatus("sent");
            
            for(Organization o:enterprise.getOrganizationDirectory().getOrganizationList()){
                if(o instanceof InvestigationOrganization){
                    invesorg=(InvestigationOrganization)o;
                    break;
                }
            }
            invesorg.getWorkQueue_receptionInvestigation().getWorkRequestList().add(toInvestigation);
            popPatientTable();
            setFieldText("");
            messagearea.setText("");
            JOptionPane.showMessageDialog(null, "request sent");
            
        }
    }//GEN-LAST:event_sendbtnActionPerformed

    private void backbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbtnActionPerformed
        // TODO add your handling code here:
        jpanel.remove(this);
        CardLayout layout = (CardLayout) jpanel.getLayout();
        layout.previous(jpanel);
    }//GEN-LAST:event_backbtnActionPerformed

    private void bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bActionPerformed

    private void popPatientTable(){
        DefaultTableModel model = (DefaultTableModel) patientTable.getModel();
        SimpleDateFormat formatter = new SimpleDateFormat("yyyy-MM-dd HH:mm");
        model.setRowCount(0);
        for(WorkRequest_quarantineCDC request:organization.getWorkQueue_quarantineCDC().getWorkRequestList()){
            Object row[]=new Object[8];
            row[0]=request;
            row[1]=formatter.format(request.getDate());
            row[2]=request.getEnterprise().getName();
            row[3]=request.getPatient().getId();
            row[4]=request.getPatient().getName();
            row[5]=request.getPatient().getGender();
            row[6]=request.getReceiver()==null?"":request.getReceiver().getEmployee().getName();
            row[7]=request.getStatus().equals("sent to CDC")?"pending":"sent";
            model.addRow(row);
            
            
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField a;
    private javax.swing.JTextField addressfield;
    private javax.swing.JTextField agefield;
    private javax.swing.JTextField b;
    private javax.swing.JButton backbtn;
    private javax.swing.JTextField birthfield;
    private javax.swing.JTextField c;
    private javax.swing.JTextField countyfield;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea messagearea;
    private javax.swing.JTable patientTable;
    private javax.swing.JTextField phonefield;
    private javax.swing.JButton selectbtn;
    private javax.swing.JButton sendbtn;
    private javax.swing.JTextField statefield;
    private javax.swing.JTextArea symptonfield;
    // End of variables declaration//GEN-END:variables
}
