/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.PoliceRole;

import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author user
 */
public class PoliceJFrame extends javax.swing.JFrame {

    /**
     * Creates new form PoliceJFrame
     */
    

    PoliceJFrame(String id, String name, String address, String phone, String enddate,String picture) {
          initComponents();
          idt.setText(id);
          adt.setText(address);
          namet.setText(name);
          pht.setText(phone);
          endt.setText(enddate);
          ImageIcon c=new ImageIcon(picture);
        ImageIcon imageIcon = new ImageIcon(c.getImage().getScaledInstance(510, 470, Image.SCALE_DEFAULT));
        
          imlabel.setIcon(imageIcon);
          setDefaultCloseOperation(this.DISPOSE_ON_CLOSE);
    }

   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        adt = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        namet = new javax.swing.JTextField();
        pht = new javax.swing.JTextField();
        idt = new javax.swing.JTextField();
        endt = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        imlabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        adt.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        adt.setForeground(new java.awt.Color(0, 153, 204));
        adt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adtActionPerformed(evt);
            }
        });
        jPanel2.add(adt, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 350, 180, -1));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 204));
        jLabel1.setText("ID");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 120, -1, 31));

        namet.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        namet.setForeground(new java.awt.Color(0, 153, 204));
        jPanel2.add(namet, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 190, 180, -1));

        pht.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        pht.setForeground(new java.awt.Color(0, 153, 204));
        jPanel2.add(pht, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 270, 180, -1));

        idt.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        idt.setForeground(new java.awt.Color(0, 153, 204));
        jPanel2.add(idt, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 120, 180, -1));

        endt.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        endt.setForeground(new java.awt.Color(0, 153, 204));
        jPanel2.add(endt, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 420, 180, -1));

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 153, 204));
        jLabel5.setText("END DATE:");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(83, 427, -1, -1));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 153, 204));
        jLabel2.setText("NAME");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 200, -1, -1));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 153, 204));
        jLabel3.setText("PHONE");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 280, -1, -1));

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 153, 204));
        jLabel4.setText("ADDRESS");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 360, -1, -1));
        jPanel2.add(imlabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 80, 510, 470));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 990, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void adtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_adtActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PoliceJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PoliceJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PoliceJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PoliceJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField adt;
    private javax.swing.JTextField endt;
    private javax.swing.JTextField idt;
    private javax.swing.JLabel imlabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField namet;
    private javax.swing.JTextField pht;
    // End of variables declaration//GEN-END:variables
}
