/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.DocumentRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Enterprise.HospitalEnterprise;
import People.MedicalRecord;
import People.People;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Image;
import java.util.ArrayList;
import javax.swing.ButtonGroup;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author stacyhuang
 */
public class ManagePatientJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManagePatientJPanel
     */
    private JPanel jpanel;
    private HospitalEnterprise enterprise;
    private EcoSystem system;
    private People thispeople;
    private ButtonGroup bgroup;
    public ManagePatientJPanel(JPanel jpanel, Enterprise enterprise, EcoSystem system) {
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        initComponents();
        this.jpanel=jpanel;
        this.enterprise=(HospitalEnterprise)enterprise;
        this.system=system;
        this.thispeople=null;
        setFieldEdible(false);  
        savebtn.setEnabled(false);updatebtn.setEnabled(true);
        this.bgroup=new ButtonGroup();
        bgroup.add(no);bgroup.add(yes);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        patientIdfield = new javax.swing.JTextField();
        searchbtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        idfield = new javax.swing.JTextField();
        namefield = new javax.swing.JTextField();
        agefield = new javax.swing.JTextField();
        birthdayfield = new javax.swing.JTextField();
        phonefield = new javax.swing.JTextField();
        addressfield = new javax.swing.JTextField();
        imageLabel = new javax.swing.JLabel();
        countyfield = new javax.swing.JTextField();
        statefield = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        emergencynamefield = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        emergencyphonefield = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        chronicfield = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        operationfield = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        pastfield = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        familyfield = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        updatebtn = new javax.swing.JButton();
        savebtn = new javax.swing.JButton();
        operationfieldupdate = new javax.swing.JTextField();
        operationadd = new javax.swing.JButton();
        chronicfieldupdate = new javax.swing.JTextField();
        chronicadd = new javax.swing.JButton();
        pastfieldupdate = new javax.swing.JTextField();
        pastadd = new javax.swing.JButton();
        familyfieldupdate = new javax.swing.JTextField();
        familyadd = new javax.swing.JButton();
        yes = new javax.swing.JRadioButton();
        no = new javax.swing.JRadioButton();
        jLabel20 = new javax.swing.JLabel();
        genderfield = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        allergyfield = new javax.swing.JTextField();
        allergyfieldupdate = new javax.swing.JTextField();
        allergyadd = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        heightfield = new javax.swing.JTextField();
        weightfield = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        backbtn = new javax.swing.JButton();
        bloodcombo = new javax.swing.JComboBox();

        setBackground(new java.awt.Color(0, 102, 153));
        setForeground(new java.awt.Color(0, 153, 204));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 204));
        jLabel1.setText("search patient id:");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 36, -1, -1));

        patientIdfield.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        patientIdfield.setForeground(new java.awt.Color(0, 153, 204));
        add(patientIdfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(513, 27, 163, -1));

        searchbtn.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        searchbtn.setForeground(new java.awt.Color(255, 153, 51));
        searchbtn.setText("search");
        searchbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchbtnActionPerformed(evt);
            }
        });
        add(searchbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(732, 26, -1, -1));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 153, 204));
        jLabel2.setText("id");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(389, 100, -1, -1));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 153, 204));
        jLabel3.setText("name");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 100, -1, -1));

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 153, 204));
        jLabel4.setText("age");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(647, 160, -1, -1));

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 153, 204));
        jLabel5.setText("birthday");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(339, 160, -1, -1));

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 153, 204));
        jLabel6.setText("phone");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 106, -1, -1));

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 153, 204));
        jLabel7.setText("address");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 156, -1, -1));

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 153, 204));
        jLabel8.setText("county");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(351, 223, -1, -1));

        idfield.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        idfield.setForeground(new java.awt.Color(0, 153, 204));
        add(idfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(433, 97, 156, -1));

        namefield.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        namefield.setForeground(new java.awt.Color(0, 153, 204));
        add(namefield, new org.netbeans.lib.awtextra.AbsoluteConstraints(697, 97, 177, -1));

        agefield.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        agefield.setForeground(new java.awt.Color(0, 153, 204));
        add(agefield, new org.netbeans.lib.awtextra.AbsoluteConstraints(697, 157, 177, -1));

        birthdayfield.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        birthdayfield.setForeground(new java.awt.Color(0, 153, 204));
        add(birthdayfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(434, 157, 155, -1));

        phonefield.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        phonefield.setForeground(new java.awt.Color(0, 153, 204));
        add(phonefield, new org.netbeans.lib.awtextra.AbsoluteConstraints(961, 97, 228, -1));

        addressfield.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        addressfield.setForeground(new java.awt.Color(0, 153, 204));
        add(addressfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(961, 157, 228, -1));

        imageLabel.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        imageLabel.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 153, 51)));
        add(imageLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(72, 130, 230, 220));

        countyfield.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        countyfield.setForeground(new java.awt.Color(0, 153, 204));
        add(countyfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(434, 220, 159, -1));

        statefield.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        statefield.setForeground(new java.awt.Color(0, 153, 204));
        add(statefield, new org.netbeans.lib.awtextra.AbsoluteConstraints(961, 220, 228, -1));

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 153, 204));
        jLabel9.setText("state");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 226, -1, -1));

        jLabel10.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 153, 204));
        jLabel10.setText("blood");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 296, -1, 30));

        jLabel11.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 153, 204));
        jLabel11.setText("emergency name");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 706, -1, -1));

        emergencynamefield.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        emergencynamefield.setForeground(new java.awt.Color(0, 153, 204));
        add(emergencynamefield, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 706, 300, -1));

        jLabel12.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 153, 204));
        jLabel12.setText("emergency phone");
        add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 706, -1, -1));

        emergencyphonefield.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        emergencyphonefield.setForeground(new java.awt.Color(0, 153, 204));
        add(emergencyphonefield, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 706, 253, -1));
        add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel14.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 153, 204));
        jLabel14.setText("chronic disease");
        add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(281, 475, -1, -1));

        chronicfield.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        chronicfield.setForeground(new java.awt.Color(0, 153, 204));
        add(chronicfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(437, 472, 300, -1));

        jLabel15.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 153, 204));
        jLabel15.setText("operation history");
        add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 422, -1, -1));

        operationfield.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        operationfield.setForeground(new java.awt.Color(0, 153, 204));
        add(operationfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(437, 419, 300, -1));

        jLabel16.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 153, 204));
        jLabel16.setText("past history");
        add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 528, -1, -1));

        pastfield.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        pastfield.setForeground(new java.awt.Color(0, 153, 204));
        add(pastfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 526, 300, -1));

        jLabel17.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 153, 204));
        jLabel17.setText("family history");
        add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(303, 590, -1, -1));

        familyfield.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        familyfield.setForeground(new java.awt.Color(0, 153, 204));
        add(familyfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(441, 587, 300, -1));

        jLabel18.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 153, 204));
        jLabel18.setText("pregnancy");
        add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(92, 410, -1, -1));

        jLabel19.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 153, 204));
        jLabel19.setText("photo");
        add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(169, 96, -1, -1));
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 367, 1428, -1));

        updatebtn.setBackground(new java.awt.Color(204, 204, 204));
        updatebtn.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        updatebtn.setForeground(new java.awt.Color(255, 153, 51));
        updatebtn.setText("update/create");
        updatebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatebtnActionPerformed(evt);
            }
        });
        add(updatebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 546, 230, 70));

        savebtn.setBackground(new java.awt.Color(204, 204, 204));
        savebtn.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        savebtn.setForeground(new java.awt.Color(255, 153, 51));
        savebtn.setText("save");
        savebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savebtnActionPerformed(evt);
            }
        });
        add(savebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 656, 230, 70));

        operationfieldupdate.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        operationfieldupdate.setForeground(new java.awt.Color(0, 153, 204));
        add(operationfieldupdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(809, 419, 191, -1));

        operationadd.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        operationadd.setForeground(new java.awt.Color(255, 153, 51));
        operationadd.setText("add");
        operationadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                operationaddActionPerformed(evt);
            }
        });
        add(operationadd, new org.netbeans.lib.awtextra.AbsoluteConstraints(1029, 418, -1, -1));

        chronicfieldupdate.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        chronicfieldupdate.setForeground(new java.awt.Color(0, 153, 204));
        add(chronicfieldupdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(809, 472, 191, -1));

        chronicadd.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        chronicadd.setForeground(new java.awt.Color(255, 153, 51));
        chronicadd.setText("add");
        chronicadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chronicaddActionPerformed(evt);
            }
        });
        add(chronicadd, new org.netbeans.lib.awtextra.AbsoluteConstraints(1029, 471, -1, -1));

        pastfieldupdate.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        pastfieldupdate.setForeground(new java.awt.Color(0, 153, 204));
        add(pastfieldupdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(809, 525, 191, -1));

        pastadd.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        pastadd.setForeground(new java.awt.Color(255, 153, 51));
        pastadd.setText("add");
        pastadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pastaddActionPerformed(evt);
            }
        });
        add(pastadd, new org.netbeans.lib.awtextra.AbsoluteConstraints(1029, 524, -1, -1));

        familyfieldupdate.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        familyfieldupdate.setForeground(new java.awt.Color(0, 153, 204));
        add(familyfieldupdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(809, 587, 191, -1));

        familyadd.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        familyadd.setForeground(new java.awt.Color(255, 153, 51));
        familyadd.setText("add");
        familyadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                familyaddActionPerformed(evt);
            }
        });
        add(familyadd, new org.netbeans.lib.awtextra.AbsoluteConstraints(1029, 586, -1, -1));

        yes.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        yes.setForeground(new java.awt.Color(0, 153, 204));
        yes.setText("yes");
        add(yes, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 463, -1, -1));

        no.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        no.setForeground(new java.awt.Color(0, 153, 204));
        no.setText("no");
        add(no, new org.netbeans.lib.awtextra.AbsoluteConstraints(165, 463, -1, -1));

        jLabel20.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(0, 153, 204));
        jLabel20.setText("gender");
        add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(617, 223, -1, -1));

        genderfield.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        genderfield.setForeground(new java.awt.Color(0, 153, 204));
        add(genderfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(697, 220, 177, -1));

        jLabel21.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(0, 153, 204));
        jLabel21.setText("medicine allergy");
        add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(277, 653, -1, -1));

        allergyfield.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        allergyfield.setForeground(new java.awt.Color(0, 153, 204));
        add(allergyfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(441, 650, 300, -1));

        allergyfieldupdate.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        allergyfieldupdate.setForeground(new java.awt.Color(0, 153, 204));
        add(allergyfieldupdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(809, 651, 191, -1));

        allergyadd.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        allergyadd.setForeground(new java.awt.Color(255, 153, 51));
        allergyadd.setText("add");
        allergyadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                allergyaddActionPerformed(evt);
            }
        });
        add(allergyadd, new org.netbeans.lib.awtextra.AbsoluteConstraints(1029, 650, -1, -1));

        jLabel22.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(0, 153, 204));
        jLabel22.setText("height");
        add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(351, 296, -1, -1));

        heightfield.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        heightfield.setForeground(new java.awt.Color(0, 153, 204));
        add(heightfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(434, 293, 114, -1));

        weightfield.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        weightfield.setForeground(new java.awt.Color(0, 153, 204));
        add(weightfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(697, 293, 128, -1));

        jLabel23.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(0, 153, 204));
        jLabel23.setText("weight");
        add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 296, -1, -1));

        jLabel24.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(0, 153, 204));
        jLabel24.setText("kg");
        add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(853, 296, -1, -1));

        jLabel25.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(0, 153, 204));
        jLabel25.setText("cm");
        add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(566, 296, -1, -1));

        backbtn.setBackground(new java.awt.Color(204, 204, 204));
        backbtn.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        backbtn.setForeground(new java.awt.Color(255, 153, 51));
        backbtn.setText("back");
        backbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backbtnActionPerformed(evt);
            }
        });
        add(backbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(72, 30, 96, 42));

        bloodcombo.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        bloodcombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "--","O","A","B","AB" }));
        add(bloodcombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 296, 230, -1));
    }// </editor-fold>//GEN-END:initComponents


    private void searchbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchbtnActionPerformed
        // TODO add your handling code here:
        savebtn.setEnabled(false);updatebtn.setEnabled(true);
        emergencynamefield.setEditable(false);
        emergencyphonefield.setEditable(false);
     
        String searchId=patientIdfield.getText();
        thispeople=null;
        if(searchId.equals("")){
            JOptionPane.showMessageDialog(null, "please enter patient id to search");
            return;
        }else{
            for(People peopleFound:system.getPeopleDirectory().getPeoples()){
                if(peopleFound.getId().equals(searchId)){
                    thispeople=peopleFound;
                    break;
                }
            }
        }
            if(thispeople!=null){
                setField(thispeople.getId(),thispeople.getName(),thispeople.getBirthday(),thispeople.getAge(),thispeople.getPhone(),thispeople.getAddress(),thispeople.getCounty(),thispeople.getState(),thispeople.getPicture(),thispeople.getGender());
                MedicalRecord mr=thispeople.getMedicalRecord();
                setMedicalRecord(mr.getPregancy(),mr.getBloodType(),mr.getEmergency_contactName(),mr.getEmergency_contactPhone(),mr.getPast_history(),mr.getFamily_history(),mr.getOperation_history(),mr.getChronicDisease(),mr.getMedicineAllergy(),mr.getHeight(),mr.getWeight());
                }else{
                JOptionPane.showMessageDialog(null, "cannot find this patient, please make sure the id you enter is correct");
                patientIdfield.setText("");
                return;
            }
              
    }//GEN-LAST:event_searchbtnActionPerformed

    private void updatebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatebtnActionPerformed
        // TODO add your handling code here:
        savebtn.setEnabled(true);updatebtn.setEnabled(false);
        weightfield.setEditable(true);
        heightfield.setEditable(true);
        emergencynamefield.setEditable(true);
        emergencyphonefield.setEditable(true);
        yes.setEnabled(true);no.setEnabled(true);
        bloodcombo.setEnabled(true);
    }//GEN-LAST:event_updatebtnActionPerformed

    private void savebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savebtnActionPerformed
        // TODO add your handling code here:
        
        String emergencyname=emergencynamefield.getText();
        String emergencyphone=emergencyphonefield.getText();
        String height=heightfield.getText();
        String weight=weightfield.getText();
        if(emergencyname.equals("")||emergencyphone.equals("")){
            JOptionPane.showMessageDialog(null, "pregnancy field, emergency field cannot be blank");
            return;
        }
   
        try{
            Integer.valueOf(emergencyphone);
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "phone must be number");
            emergencyphonefield.setText("");
            return;
        }
        try{
            Double.valueOf(height);
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "height must be number");
            heightfield.setText("");
            return;
        }
        try{
            Double.valueOf(weight);
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "weight must be number");
            weightfield.setText("");
            return;
        }
        thispeople.getMedicalRecord().setHeight(Double.valueOf(height));
        thispeople.getMedicalRecord().setWeight(Double.valueOf(weight));
        thispeople.getMedicalRecord().setEmergency_contactName(emergencyname);
        thispeople.getMedicalRecord().setEmergency_contactPhone(emergencyphone);
        if(yes.isSelected()){
            thispeople.getMedicalRecord().setPregancy("yes");
        }else{
            thispeople.getMedicalRecord().setPregancy("no");
        }
        if(bloodcombo.getSelectedIndex()==0){
            JOptionPane.showMessageDialog(null, "please select blood type");
            return;
        }else{
            System.out.println((String)bloodcombo.getSelectedItem());
            thispeople.getMedicalRecord().setBloodType((String) bloodcombo.getSelectedItem());
        }
        JOptionPane.showMessageDialog(null, "create/update success");
        savebtn.setEnabled(false);updatebtn.setEnabled(true);
        emergencynamefield.setEditable(false);
        emergencyphonefield.setEditable(false);
        weightfield.setEditable(false);
        heightfield.setEditable(false);
        yes.setEnabled(false);no.setEnabled(false);
        bloodcombo.setEnabled(false);
    }//GEN-LAST:event_savebtnActionPerformed

    private void operationaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_operationaddActionPerformed
        // TODO add your handling code here:
        String operation=operationfieldupdate.getText();
        if(operation.equals("")){
            JOptionPane.showMessageDialog(null, "cannot add blank field");
            return;
        }
        thispeople.getMedicalRecord().getOperation_history().add(operation);
        operationfield.setText(convertArrayToString(thispeople.getMedicalRecord().getOperation_history()));
        operationfieldupdate.setText("");
    }//GEN-LAST:event_operationaddActionPerformed

    private void chronicaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chronicaddActionPerformed
        // TODO add your handling code here:
        String chronic=chronicfieldupdate.getText();
        if(chronic.equals("")){
            JOptionPane.showMessageDialog(null, "cannot add blank field");
            return;
        }
        thispeople.getMedicalRecord().getChronicDisease().add(chronic);
        chronicfield.setText(convertArrayToString(thispeople.getMedicalRecord().getChronicDisease()));
        chronicfieldupdate.setText("");
    }//GEN-LAST:event_chronicaddActionPerformed

    private void pastaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pastaddActionPerformed
        // TODO add your handling code here:
        String past=pastfieldupdate.getText();
        if(past.equals("")){
            JOptionPane.showMessageDialog(null, "cannot add blank field");
            return;
        }
        thispeople.getMedicalRecord().getPast_history().add(past);
        pastfield.setText(convertArrayToString(thispeople.getMedicalRecord().getPast_history()));
        pastfieldupdate.setText("");
    }//GEN-LAST:event_pastaddActionPerformed

    private void familyaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_familyaddActionPerformed
        // TODO add your handling code here:
        String family=familyfieldupdate.getText();
        if(family.equals("")){
            JOptionPane.showMessageDialog(null, "cannot add blank field");
            return;
        }
        thispeople.getMedicalRecord().getFamily_history().add(family);
        familyfield.setText(convertArrayToString(thispeople.getMedicalRecord().getFamily_history()));
        familyfieldupdate.setText("");
    }//GEN-LAST:event_familyaddActionPerformed

    private void allergyaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_allergyaddActionPerformed
        // TODO add your handling code here:
        String allergy=allergyfieldupdate.getText();
        if(allergy.equals("")){
            JOptionPane.showMessageDialog(null, "cannot add blank field");
            return;
        }
        thispeople.getMedicalRecord().getMedicineAllergy().add(allergy);
        allergyfield.setText(convertArrayToString(thispeople.getMedicalRecord().getMedicineAllergy()));
        allergyfieldupdate.setText("");
    }//GEN-LAST:event_allergyaddActionPerformed

    private void backbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbtnActionPerformed
        // TODO add your handling code here:
        jpanel.remove(this);
        CardLayout layout = (CardLayout) jpanel.getLayout();
        layout.previous(jpanel);
    }//GEN-LAST:event_backbtnActionPerformed
    private void setFieldEdible(boolean boo){
        idfield.setEditable(boo);
        namefield.setEditable(boo);
        birthdayfield.setEditable(boo);
        agefield.setEditable(boo);
        phonefield.setEditable(boo);
        addressfield.setEditable(boo);
        statefield.setEditable(boo);
        countyfield.setEditable(boo);
        emergencynamefield.setEditable(boo);
        emergencyphonefield.setEditable(boo);
        pastfield.setEditable(boo);
        operationfield.setEditable(boo);
        familyfield.setEditable(boo);
        chronicfield.setEditable(boo);
        allergyfield.setEditable(boo);
        yes.setEnabled(boo);
        no.setEnabled(boo);
        bloodcombo.setEnabled(boo);
        genderfield.setEditable(boo);
        heightfield.setEditable(boo);
        weightfield.setEditable(boo);
    }
    private void setField(String id,String name, String birthday,int age,String phone,String address,String county,String state,String picture,String gender){
        idfield.setText(id);
        namefield.setText(name);
        birthdayfield.setText(birthday);
        agefield.setText(String.valueOf(age));
        phonefield.setText(phone);
        addressfield.setText(address);
        statefield.setText(state);
        countyfield.setText(county);
        ImageIcon c=new ImageIcon(picture);
        ImageIcon imageIcon = new ImageIcon(c.getImage().getScaledInstance(230, 220, Image.SCALE_DEFAULT));
        
          
        imageLabel.setIcon(imageIcon);
        genderfield.setText(gender);
    }
    private void setMedicalRecord(String pregnancy,String blood,String emergency_name,String emergency_phone,ArrayList<String>past,ArrayList<String>family,ArrayList<String>operation,ArrayList<String>chronic,ArrayList<String>allergy,double height,double weight){

        if(blood.equals("")){
            bloodcombo.setSelectedItem("--");
        }else{
            bloodcombo.setSelectedItem(blood);}
        if(pregnancy.equals("yes")){
            yes.setSelected(true);
        }else if(pregnancy.equals("no")){
            no.setSelected(true);
        }else if(pregnancy.equals("")){
            bgroup.clearSelection();
        }
        emergencynamefield.setText(emergency_name);
        emergencyphonefield.setText(emergency_phone);
        pastfield.setText(convertArrayToString(past));
        operationfield.setText(convertArrayToString(operation));
        familyfield.setText(convertArrayToString(family));
        chronicfield.setText(convertArrayToString(chronic));
        allergyfield.setText(convertArrayToString(allergy));
        heightfield.setText(String.valueOf(height));
        weightfield.setText(String.valueOf(weight));
    }
    private String convertArrayToString(ArrayList<String> arr){
        String toReturn="";
        if(arr.size()!=0){
            toReturn=arr.get(0);
            for(int i=1;i<arr.size(); i++){
                toReturn=toReturn+","+arr.get(i);
            }
        }else{
            toReturn="";
        }
        
        return toReturn;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField addressfield;
    private javax.swing.JTextField agefield;
    private javax.swing.JButton allergyadd;
    private javax.swing.JTextField allergyfield;
    private javax.swing.JTextField allergyfieldupdate;
    private javax.swing.JButton backbtn;
    private javax.swing.JTextField birthdayfield;
    private javax.swing.JComboBox<String> bloodcombo;
    private javax.swing.JButton chronicadd;
    private javax.swing.JTextField chronicfield;
    private javax.swing.JTextField chronicfieldupdate;
    private javax.swing.JTextField countyfield;
    private javax.swing.JTextField emergencynamefield;
    private javax.swing.JTextField emergencyphonefield;
    private javax.swing.JButton familyadd;
    private javax.swing.JTextField familyfield;
    private javax.swing.JTextField familyfieldupdate;
    private javax.swing.JTextField genderfield;
    private javax.swing.JTextField heightfield;
    private javax.swing.JTextField idfield;
    private javax.swing.JLabel imageLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField namefield;
    private javax.swing.JRadioButton no;
    private javax.swing.JButton operationadd;
    private javax.swing.JTextField operationfield;
    private javax.swing.JTextField operationfieldupdate;
    private javax.swing.JButton pastadd;
    private javax.swing.JTextField pastfield;
    private javax.swing.JTextField pastfieldupdate;
    private javax.swing.JTextField patientIdfield;
    private javax.swing.JTextField phonefield;
    private javax.swing.JButton savebtn;
    private javax.swing.JButton searchbtn;
    private javax.swing.JTextField statefield;
    private javax.swing.JButton updatebtn;
    private javax.swing.JTextField weightfield;
    private javax.swing.JRadioButton yes;
    // End of variables declaration//GEN-END:variables
}
